### ISSUE TITLE
Unable to convert BigInteger to Decimal in spark 2.1.1

### ISSUE THREAD

**Issue by skattoju-zz** [ZuInnoTe/spark-hadoopcryptoledger-ds#18]
There is an issue with the 1.2.0 version of hadoopcryptoledger on spark 2.1.1. It works ok on spark 2.2.1
  
   / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /__ / .__/\_,_/_/ /_/\_\   version 2.1.1
      /_/

Using Python version 3.5.4 (default, Dec  4 2017 16:30:40)
SparkSession available as 'spark'.
>>> df = sqlContext.read.format('org.zuinnote.spark.ethereum.block').options(enrich='false').load('/home/skattoju/project/skattoju/ethereum-test-data')
>>> df.show()
18/03/17 09:44:54 ERROR Executor: Exception in task 0.0 in stage 0.0 (TID 0)
java.lang.IllegalArgumentException: requirement failed: BigInteger 39000000000000000000 too large for decimal
//stacktrace excluded

**Comment by jornfranke** [comment]
This is a limitation of Spark SQL and cannot be fixed: 
see https://issues.apache.org/jira/browse/SPARK-20341

I just documented this in the readme
https://github.com/ZuInnoTe/spark-hadoopcryptoledger-ds/blob/master/README.md

I propose to upgrade to Spark 2.3 which seems to be more reliable. 

Please close if you agree.

**Comment by jornfranke** [comment]
Another alternative is to work with the hadoopcryptoledger library in Spark directly, this works with any Spark version:
https://github.com/ZuInnoTe/hadoopcryptoledger/wiki/Use-Spark-to-count-the-number-of-transactions-from-files-containing-Ethereum-Blockchain-data

**Comment by skattoju-zz** [comment]
agreed.
